export const BREEDS = [
  { name: "Kelso", origin: "USA", characteristics: "Smart fighter, agile, excellent cutting ability" },
  { name: "Hatch", origin: "USA", characteristics: "Powerful, aggressive, strong shuffler" },
  { name: "Sweater", origin: "USA", characteristics: "Fast, high station, excellent aerial fighter" },
  { name: "Roundhead", origin: "USA", characteristics: "Smart, side-stepping, excellent cutter" },
  { name: "Lemon", origin: "USA", characteristics: "Fast, flashy, great cutting ability" },
  { name: "Albany", origin: "USA", characteristics: "Beautiful plumage, good cutter, smart fighter" },
  { name: "Claret", origin: "USA", characteristics: "Powerful, deep game, strong shuffler" },
  { name: "Grey", origin: "USA", characteristics: "Fast, smart, excellent side-stepper" },
  { name: "Butcher", origin: "USA", characteristics: "Aggressive, powerful hitter, good stamina" },
  { name: "Radio", origin: "Philippines", characteristics: "Fast, high-flying, aggressive" },
  { name: "Texas", origin: "USA", characteristics: "Power hitter, strong body, good cutter" },
  { name: "Peruvian", origin: "Peru", characteristics: "Tall, long-reaching, aggressive" },
  { name: "Asil", origin: "India", characteristics: "Ancient breed, powerful, extremely game" },
  { name: "Shamo", origin: "Japan", characteristics: "Tall, muscular, powerful fighter" },
  { name: "Spanish", origin: "Spain", characteristics: "Elegant, quick, good cutting ability" },
  { name: "Mug", origin: "USA", characteristics: "Compact, powerful, excellent shuffler" },
  { name: "Typewriter", origin: "Philippines", characteristics: "Rapid-fire hitting, fast combination puncher" },
  { name: "Democrat", origin: "USA", characteristics: "Well-rounded fighter, good cutting ability" },
  { name: "Blueface", origin: "USA", characteristics: "Distinctive blue face, powerful, game" },
  { name: "Brown Red", origin: "USA", characteristics: "Strong, aggressive, good cutter" },
  { name: "Other", origin: "Various", characteristics: "Mixed or unlisted breed" },
] as const;

export const BLOODLINES = [
  { breed: "Kelso", name: "Lemon 84", breeder: "Walter Kelso" },
  { breed: "Kelso", name: "Out & Out Kelso", breeder: "Walter Kelso" },
  { breed: "Kelso", name: "Yellow-Legged Kelso", breeder: "Various" },
  { breed: "Hatch", name: "Blueface Hatch", breeder: "Sanford Hatch" },
  { breed: "Hatch", name: "McLean Hatch", breeder: "Johnny McLean" },
  { breed: "Hatch", name: "Yellow-Legged Hatch", breeder: "Various" },
  { breed: "Sweater", name: "Original Sweater", breeder: "Carol Nesmith" },
  { breed: "Sweater", name: "Sweater-Kelso Cross", breeder: "Various" },
  { breed: "Roundhead", name: "Allen Roundhead", breeder: "Various" },
  { breed: "Roundhead", name: "Lacy Roundhead", breeder: "Judge Lacy" },
  { breed: "Lemon", name: "Lemon 84", breeder: "Various" },
  { breed: "Albany", name: "Regular Albany", breeder: "Various" },
  { breed: "Claret", name: "Regular Claret", breeder: "Various" },
  { breed: "Grey", name: "Regular Grey", breeder: "Various" },
] as const;
