export interface Province {
  name: string;
  region: string;
  cities: string[];
}

export const PROVINCES: Province[] = [
  { name: "Abra", region: "CAR", cities: ["Bangued", "Lagangilang", "Tayum", "Dolores"] },
  { name: "Agusan del Norte", region: "XIII", cities: ["Butuan", "Cabadbaran", "Buenavista", "Nasipit"] },
  { name: "Agusan del Sur", region: "XIII", cities: ["Bayugan", "Prosperidad", "San Francisco", "Rosario"] },
  { name: "Aklan", region: "VI", cities: ["Kalibo", "Malay", "Altavas", "Banga"] },
  { name: "Albay", region: "V", cities: ["Legazpi", "Tabaco", "Ligao", "Daraga", "Guinobatan"] },
  { name: "Antique", region: "VI", cities: ["San Jose de Buenavista", "Sibalom", "Culasi"] },
  { name: "Apayao", region: "CAR", cities: ["Kabugao", "Luna", "Conner"] },
  { name: "Aurora", region: "III", cities: ["Baler", "Maria Aurora", "Casiguran"] },
  { name: "Bataan", region: "III", cities: ["Balanga", "Mariveles", "Dinalupihan", "Orion"] },
  { name: "Batanes", region: "II", cities: ["Basco", "Itbayat", "Ivana"] },
  { name: "Batangas", region: "IV-A", cities: ["Batangas City", "Lipa", "Tanauan", "Santo Tomas", "Nasugbu"] },
  { name: "Benguet", region: "CAR", cities: ["Baguio", "La Trinidad", "Itogon", "Tuba"] },
  { name: "Bohol", region: "VII", cities: ["Tagbilaran", "Ubay", "Talibon", "Jagna", "Carmen"] },
  { name: "Bukidnon", region: "X", cities: ["Malaybalay", "Valencia", "Maramag", "Don Carlos"] },
  { name: "Bulacan", region: "III", cities: ["Malolos", "Meycauayan", "San Jose del Monte", "Marilao", "Bocaue", "Guiguinto"] },
  { name: "Cagayan", region: "II", cities: ["Tuguegarao", "Aparri", "Solana", "Enrile"] },
  { name: "Camarines Norte", region: "V", cities: ["Daet", "Jose Panganiban", "Labo"] },
  { name: "Camarines Sur", region: "V", cities: ["Naga", "Iriga", "Pili", "Calabanga"] },
  { name: "Camiguin", region: "X", cities: ["Mambajao", "Catarman", "Sagay"] },
  { name: "Capiz", region: "VI", cities: ["Roxas City", "Panay", "Pontevedra"] },
  { name: "Catanduanes", region: "V", cities: ["Virac", "San Andres", "Bato"] },
  { name: "Cavite", region: "IV-A", cities: ["Imus", "Bacoor", "Dasmarinas", "General Trias", "Cavite City", "Tagaytay"] },
  { name: "Cebu", region: "VII", cities: ["Cebu City", "Mandaue", "Lapu-Lapu", "Talisay", "Toledo", "Carcar"] },
  { name: "Cotabato", region: "XII", cities: ["Kidapawan", "Kabacan", "Matalam", "Midsayap"] },
  { name: "Davao de Oro", region: "XI", cities: ["Nabunturan", "Monkayo", "Compostela", "Montevista"] },
  { name: "Davao del Norte", region: "XI", cities: ["Tagum", "Panabo", "Island Garden City of Samal", "Carmen"] },
  { name: "Davao del Sur", region: "XI", cities: ["Davao City", "Digos", "Bansalan", "Hagonoy"] },
  { name: "Davao Occidental", region: "XI", cities: ["Malita", "Santa Maria", "Don Marcelino"] },
  { name: "Davao Oriental", region: "XI", cities: ["Mati", "Baganga", "Lupon", "Cateel"] },
  { name: "Eastern Samar", region: "VIII", cities: ["Borongan", "Guiuan", "Oras"] },
  { name: "Guimaras", region: "VI", cities: ["Jordan", "Buenavista", "Nueva Valencia"] },
  { name: "Ifugao", region: "CAR", cities: ["Lagawe", "Banaue", "Kiangan"] },
  { name: "Ilocos Norte", region: "I", cities: ["Laoag", "Batac", "Paoay", "Pagudpud"] },
  { name: "Ilocos Sur", region: "I", cities: ["Vigan", "Candon", "Narvacan", "Santa Maria"] },
  { name: "Iloilo", region: "VI", cities: ["Iloilo City", "Passi", "Santa Barbara", "Pototan", "Oton"] },
  { name: "Isabela", region: "II", cities: ["Ilagan", "Cauayan", "Santiago", "Roxas"] },
  { name: "Kalinga", region: "CAR", cities: ["Tabuk", "Rizal", "Pinukpuk"] },
  { name: "La Union", region: "I", cities: ["San Fernando", "Agoo", "Bauang", "Rosario"] },
  { name: "Laguna", region: "IV-A", cities: ["Santa Cruz", "San Pablo", "Calamba", "Binan", "Santa Rosa", "Cabuyao"] },
  { name: "Lanao del Norte", region: "X", cities: ["Iligan", "Tubod", "Kapatagan"] },
  { name: "Lanao del Sur", region: "BARMM", cities: ["Marawi", "Malabang", "Wao"] },
  { name: "Leyte", region: "VIII", cities: ["Tacloban", "Ormoc", "Baybay", "Palo"] },
  { name: "Maguindanao del Norte", region: "BARMM", cities: ["Cotabato City", "Sultan Kudarat", "Datu Odin Sinsuat"] },
  { name: "Maguindanao del Sur", region: "BARMM", cities: ["Buluan", "Datu Paglas", "General S. K. Pendatun"] },
  { name: "Marinduque", region: "IV-B", cities: ["Boac", "Mogpog", "Gasan"] },
  { name: "Masbate", region: "V", cities: ["Masbate City", "Aroroy", "Mandaon"] },
  { name: "Metro Manila", region: "NCR", cities: ["Manila", "Quezon City", "Makati", "Taguig", "Pasig", "Mandaluyong", "Pasay", "Paranaque", "Caloocan", "Muntinlupa", "Las Pinas", "Marikina", "Valenzuela", "Malabon", "Navotas", "San Juan", "Pateros"] },
  { name: "Misamis Occidental", region: "X", cities: ["Oroquieta", "Ozamiz", "Tangub", "Clarin"] },
  { name: "Misamis Oriental", region: "X", cities: ["Cagayan de Oro", "Gingoog", "El Salvador", "Villanueva"] },
  { name: "Mountain Province", region: "CAR", cities: ["Bontoc", "Sagada", "Besao"] },
  { name: "Negros Occidental", region: "VI", cities: ["Bacolod", "Silay", "Talisay", "Kabankalan", "Sagay", "San Carlos"] },
  { name: "Negros Oriental", region: "VII", cities: ["Dumaguete", "Bais", "Tanjay", "Bayawan", "Guihulngan"] },
  { name: "Northern Samar", region: "VIII", cities: ["Catarman", "Allen", "Laoang"] },
  { name: "Nueva Ecija", region: "III", cities: ["Cabanatuan", "Palayan", "San Jose", "Gapan", "Munoz"] },
  { name: "Nueva Vizcaya", region: "II", cities: ["Bayombong", "Solano", "Bambang"] },
  { name: "Occidental Mindoro", region: "IV-B", cities: ["Mamburao", "San Jose", "Sablayan"] },
  { name: "Oriental Mindoro", region: "IV-B", cities: ["Calapan", "Puerto Galera", "Pinamalayan", "Roxas"] },
  { name: "Palawan", region: "IV-B", cities: ["Puerto Princesa", "El Nido", "Coron", "Brooke's Point"] },
  { name: "Pampanga", region: "III", cities: ["San Fernando", "Angeles", "Mabalacat", "Apalit", "Mexico", "Porac"] },
  { name: "Pangasinan", region: "I", cities: ["Dagupan", "Lingayen", "San Carlos", "Urdaneta", "Alaminos"] },
  { name: "Quezon", region: "IV-A", cities: ["Lucena", "Tayabas", "Sariaya", "Candelaria", "Pagbilao"] },
  { name: "Quirino", region: "II", cities: ["Cabarroguis", "Diffun", "Saguday"] },
  { name: "Rizal", region: "IV-A", cities: ["Antipolo", "Taytay", "Cainta", "Binangonan", "Rodriguez"] },
  { name: "Romblon", region: "IV-B", cities: ["Romblon", "Odiongan", "Cajidiocan"] },
  { name: "Samar", region: "VIII", cities: ["Catbalogan", "Calbayog", "Basey"] },
  { name: "Sarangani", region: "XII", cities: ["Alabel", "Glan", "Malapatan"] },
  { name: "Siquijor", region: "VII", cities: ["Siquijor", "Larena", "San Juan"] },
  { name: "Sorsogon", region: "V", cities: ["Sorsogon City", "Bulan", "Irosin", "Casiguran"] },
  { name: "South Cotabato", region: "XII", cities: ["Koronadal", "General Santos", "Polomolok", "Tupi"] },
  { name: "Southern Leyte", region: "VIII", cities: ["Maasin", "Sogod", "Hinunangan"] },
  { name: "Sultan Kudarat", region: "XII", cities: ["Isulan", "Tacurong", "Kalamansig"] },
  { name: "Sulu", region: "BARMM", cities: ["Jolo", "Patikul", "Indanan"] },
  { name: "Surigao del Norte", region: "XIII", cities: ["Surigao City", "Dapa", "Del Carmen"] },
  { name: "Surigao del Sur", region: "XIII", cities: ["Tandag", "Bislig", "Lianga"] },
  { name: "Tarlac", region: "III", cities: ["Tarlac City", "Concepcion", "Paniqui", "Capas"] },
  { name: "Tawi-Tawi", region: "BARMM", cities: ["Bongao", "Panglima Sugala", "Languyan"] },
  { name: "Zambales", region: "III", cities: ["Olongapo", "Iba", "Subic", "San Narciso"] },
  { name: "Zamboanga del Norte", region: "IX", cities: ["Dipolog", "Dapitan", "Sindangan"] },
  { name: "Zamboanga del Sur", region: "IX", cities: ["Pagadian", "Zamboanga City", "Molave", "Aurora"] },
  { name: "Zamboanga Sibugay", region: "IX", cities: ["Ipil", "Kabasalan", "Buug"] },
];

export const PROVINCE_NAMES = PROVINCES.map((p) => p.name);
